'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WS_MaisEscola_Admin
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AdminSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Admin
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private WS1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private WS2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private WS3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private WS6OperationCompleted As System.Threading.SendOrPostCallback
        
        Private WS7OperationCompleted As System.Threading.SendOrPostCallback
        
        Private WS4OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Mais_Escola.My.MySettings.Default.Mais_Escola_WS_MaisEscola_Admin_Admin
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event WS1Completed As WS1CompletedEventHandler
        
        '''<remarks/>
        Public Event WS2Completed As WS2CompletedEventHandler
        
        '''<remarks/>
        Public Event WS3Completed As WS3CompletedEventHandler
        
        '''<remarks/>
        Public Event WS6Completed As WS6CompletedEventHandler
        
        '''<remarks/>
        Public Event WS7Completed As WS7CompletedEventHandler
        
        '''<remarks/>
        Public Event WS4Completed As WS4CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WS1(ByVal maquina As String, ByVal cnpj As String) As String
            Dim results() As Object = Me.Invoke("WS1", New Object() {maquina, cnpj})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WS1Async(ByVal maquina As String, ByVal cnpj As String)
            Me.WS1Async(maquina, cnpj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WS1Async(ByVal maquina As String, ByVal cnpj As String, ByVal userState As Object)
            If (Me.WS1OperationCompleted Is Nothing) Then
                Me.WS1OperationCompleted = AddressOf Me.OnWS1OperationCompleted
            End If
            Me.InvokeAsync("WS1", New Object() {maquina, cnpj}, Me.WS1OperationCompleted, userState)
        End Sub
        
        Private Sub OnWS1OperationCompleted(ByVal arg As Object)
            If (Not (Me.WS1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WS1Completed(Me, New WS1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WS2(ByVal bd As String, ByVal nome As String, ByVal responsavel As String, ByVal cnpj As String, ByVal maquina As String, ByVal mes As String, ByVal data As String) As String
            Dim results() As Object = Me.Invoke("WS2", New Object() {bd, nome, responsavel, cnpj, maquina, mes, data})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WS2Async(ByVal bd As String, ByVal nome As String, ByVal responsavel As String, ByVal cnpj As String, ByVal maquina As String, ByVal mes As String, ByVal data As String)
            Me.WS2Async(bd, nome, responsavel, cnpj, maquina, mes, data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WS2Async(ByVal bd As String, ByVal nome As String, ByVal responsavel As String, ByVal cnpj As String, ByVal maquina As String, ByVal mes As String, ByVal data As String, ByVal userState As Object)
            If (Me.WS2OperationCompleted Is Nothing) Then
                Me.WS2OperationCompleted = AddressOf Me.OnWS2OperationCompleted
            End If
            Me.InvokeAsync("WS2", New Object() {bd, nome, responsavel, cnpj, maquina, mes, data}, Me.WS2OperationCompleted, userState)
        End Sub
        
        Private Sub OnWS2OperationCompleted(ByVal arg As Object)
            If (Not (Me.WS2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WS2Completed(Me, New WS2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS3", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WS3(ByVal maquina As String, ByVal bd As String) As String
            Dim results() As Object = Me.Invoke("WS3", New Object() {maquina, bd})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WS3Async(ByVal maquina As String, ByVal bd As String)
            Me.WS3Async(maquina, bd, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WS3Async(ByVal maquina As String, ByVal bd As String, ByVal userState As Object)
            If (Me.WS3OperationCompleted Is Nothing) Then
                Me.WS3OperationCompleted = AddressOf Me.OnWS3OperationCompleted
            End If
            Me.InvokeAsync("WS3", New Object() {maquina, bd}, Me.WS3OperationCompleted, userState)
        End Sub
        
        Private Sub OnWS3OperationCompleted(ByVal arg As Object)
            If (Not (Me.WS3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WS3Completed(Me, New WS3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS6", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WS6(ByVal Empresa As String, ByVal bd As String, ByVal mensagem As String) As String
            Dim results() As Object = Me.Invoke("WS6", New Object() {Empresa, bd, mensagem})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WS6Async(ByVal Empresa As String, ByVal bd As String, ByVal mensagem As String)
            Me.WS6Async(Empresa, bd, mensagem, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WS6Async(ByVal Empresa As String, ByVal bd As String, ByVal mensagem As String, ByVal userState As Object)
            If (Me.WS6OperationCompleted Is Nothing) Then
                Me.WS6OperationCompleted = AddressOf Me.OnWS6OperationCompleted
            End If
            Me.InvokeAsync("WS6", New Object() {Empresa, bd, mensagem}, Me.WS6OperationCompleted, userState)
        End Sub
        
        Private Sub OnWS6OperationCompleted(ByVal arg As Object)
            If (Not (Me.WS6CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WS6Completed(Me, New WS6CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS7", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WS7(ByVal Antigo As String, ByVal Novo As String) As String
            Dim results() As Object = Me.Invoke("WS7", New Object() {Antigo, Novo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WS7Async(ByVal Antigo As String, ByVal Novo As String)
            Me.WS7Async(Antigo, Novo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WS7Async(ByVal Antigo As String, ByVal Novo As String, ByVal userState As Object)
            If (Me.WS7OperationCompleted Is Nothing) Then
                Me.WS7OperationCompleted = AddressOf Me.OnWS7OperationCompleted
            End If
            Me.InvokeAsync("WS7", New Object() {Antigo, Novo}, Me.WS7OperationCompleted, userState)
        End Sub
        
        Private Sub OnWS7OperationCompleted(ByVal arg As Object)
            If (Not (Me.WS7CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WS7Completed(Me, New WS7CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS4", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WS4(ByVal cnpj As String) As String
            Dim results() As Object = Me.Invoke("WS4", New Object() {cnpj})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub WS4Async(ByVal cnpj As String)
            Me.WS4Async(cnpj, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WS4Async(ByVal cnpj As String, ByVal userState As Object)
            If (Me.WS4OperationCompleted Is Nothing) Then
                Me.WS4OperationCompleted = AddressOf Me.OnWS4OperationCompleted
            End If
            Me.InvokeAsync("WS4", New Object() {cnpj}, Me.WS4OperationCompleted, userState)
        End Sub
        
        Private Sub OnWS4OperationCompleted(ByVal arg As Object)
            If (Not (Me.WS4CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WS4Completed(Me, New WS4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub WS1CompletedEventHandler(ByVal sender As Object, ByVal e As WS1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WS1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub WS2CompletedEventHandler(ByVal sender As Object, ByVal e As WS2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WS2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub WS3CompletedEventHandler(ByVal sender As Object, ByVal e As WS3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WS3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub WS6CompletedEventHandler(ByVal sender As Object, ByVal e As WS6CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WS6CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub WS7CompletedEventHandler(ByVal sender As Object, ByVal e As WS7CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WS7CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub WS4CompletedEventHandler(ByVal sender As Object, ByVal e As WS4CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WS4CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
