'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WS_MaisEscola_Delib11
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Delib11Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Delib11
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private trazerFichaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private trazerFicha2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private trazerNroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GradeTurmaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private idDelibNFOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultaOpcoesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultaFichaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private preencherFichaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultaCategoriaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Mais_Escola.My.MySettings.Default.Mais_Escola_WS_MaisEscola_Delib11_Delib11
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event trazerFichaCompleted As trazerFichaCompletedEventHandler
        
        '''<remarks/>
        Public Event trazerFicha2Completed As trazerFicha2CompletedEventHandler
        
        '''<remarks/>
        Public Event trazerNroCompleted As trazerNroCompletedEventHandler
        
        '''<remarks/>
        Public Event GradeTurmaCompleted As GradeTurmaCompletedEventHandler
        
        '''<remarks/>
        Public Event idDelibNFCompleted As idDelibNFCompletedEventHandler
        
        '''<remarks/>
        Public Event consultaOpcoesCompleted As consultaOpcoesCompletedEventHandler
        
        '''<remarks/>
        Public Event consultaFichaCompleted As consultaFichaCompletedEventHandler
        
        '''<remarks/>
        Public Event preencherFichaCompleted As preencherFichaCompletedEventHandler
        
        '''<remarks/>
        Public Event consultaCategoriaCompleted As consultaCategoriaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/trazerFicha", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function trazerFicha(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal CodigoTurma As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("trazerFicha", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, CodigoTurma})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub trazerFichaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal CodigoTurma As String)
            Me.trazerFichaAsync(UsuarioWeb, SenhaWeb, Escola, AnoVigente, CodigoTurma, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub trazerFichaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal CodigoTurma As String, ByVal userState As Object)
            If (Me.trazerFichaOperationCompleted Is Nothing) Then
                Me.trazerFichaOperationCompleted = AddressOf Me.OntrazerFichaOperationCompleted
            End If
            Me.InvokeAsync("trazerFicha", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, CodigoTurma}, Me.trazerFichaOperationCompleted, userState)
        End Sub
        
        Private Sub OntrazerFichaOperationCompleted(ByVal arg As Object)
            If (Not (Me.trazerFichaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent trazerFichaCompleted(Me, New trazerFichaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/trazerFicha2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function trazerFicha2(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal CodigoTurma As String, ByVal NroAluno As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("trazerFicha2", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, CodigoTurma, NroAluno})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub trazerFicha2Async(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal CodigoTurma As String, ByVal NroAluno As String)
            Me.trazerFicha2Async(UsuarioWeb, SenhaWeb, Escola, AnoVigente, CodigoTurma, NroAluno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub trazerFicha2Async(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal CodigoTurma As String, ByVal NroAluno As String, ByVal userState As Object)
            If (Me.trazerFicha2OperationCompleted Is Nothing) Then
                Me.trazerFicha2OperationCompleted = AddressOf Me.OntrazerFicha2OperationCompleted
            End If
            Me.InvokeAsync("trazerFicha2", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, CodigoTurma, NroAluno}, Me.trazerFicha2OperationCompleted, userState)
        End Sub
        
        Private Sub OntrazerFicha2OperationCompleted(ByVal arg As Object)
            If (Not (Me.trazerFicha2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent trazerFicha2Completed(Me, New trazerFicha2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/trazerNro", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function trazerNro(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String) As String
            Dim results() As Object = Me.Invoke("trazerNro", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub trazerNroAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String)
            Me.trazerNroAsync(UsuarioWeb, SenhaWeb, Escola, AnoVigente, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub trazerNroAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal userState As Object)
            If (Me.trazerNroOperationCompleted Is Nothing) Then
                Me.trazerNroOperationCompleted = AddressOf Me.OntrazerNroOperationCompleted
            End If
            Me.InvokeAsync("trazerNro", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente}, Me.trazerNroOperationCompleted, userState)
        End Sub
        
        Private Sub OntrazerNroOperationCompleted(ByVal arg As Object)
            If (Not (Me.trazerNroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent trazerNroCompleted(Me, New trazerNroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GradeTurma", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GradeTurma(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal Bimestre As String, ByVal Turma As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GradeTurma", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, Bimestre, Turma})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GradeTurmaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal Bimestre As String, ByVal Turma As String)
            Me.GradeTurmaAsync(UsuarioWeb, SenhaWeb, Escola, AnoVigente, Bimestre, Turma, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GradeTurmaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal Bimestre As String, ByVal Turma As String, ByVal userState As Object)
            If (Me.GradeTurmaOperationCompleted Is Nothing) Then
                Me.GradeTurmaOperationCompleted = AddressOf Me.OnGradeTurmaOperationCompleted
            End If
            Me.InvokeAsync("GradeTurma", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, Bimestre, Turma}, Me.GradeTurmaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGradeTurmaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GradeTurmaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GradeTurmaCompleted(Me, New GradeTurmaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/idDelibNF", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function idDelibNF(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal Turma As String, ByVal NroAluno As String) As String
            Dim results() As Object = Me.Invoke("idDelibNF", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, Turma, NroAluno})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub idDelibNFAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal Turma As String, ByVal NroAluno As String)
            Me.idDelibNFAsync(UsuarioWeb, SenhaWeb, Escola, AnoVigente, Turma, NroAluno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub idDelibNFAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal AnoVigente As String, ByVal Turma As String, ByVal NroAluno As String, ByVal userState As Object)
            If (Me.idDelibNFOperationCompleted Is Nothing) Then
                Me.idDelibNFOperationCompleted = AddressOf Me.OnidDelibNFOperationCompleted
            End If
            Me.InvokeAsync("idDelibNF", New Object() {UsuarioWeb, SenhaWeb, Escola, AnoVigente, Turma, NroAluno}, Me.idDelibNFOperationCompleted, userState)
        End Sub
        
        Private Sub OnidDelibNFOperationCompleted(ByVal arg As Object)
            If (Not (Me.idDelibNFCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent idDelibNFCompleted(Me, New idDelibNFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaOpcoes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaOpcoes(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal Categoria As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("consultaOpcoes", New Object() {UsuarioWeb, SenhaWeb, Escola, Categoria})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaOpcoesAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal Categoria As String)
            Me.consultaOpcoesAsync(UsuarioWeb, SenhaWeb, Escola, Categoria, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaOpcoesAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal Categoria As String, ByVal userState As Object)
            If (Me.consultaOpcoesOperationCompleted Is Nothing) Then
                Me.consultaOpcoesOperationCompleted = AddressOf Me.OnconsultaOpcoesOperationCompleted
            End If
            Me.InvokeAsync("consultaOpcoes", New Object() {UsuarioWeb, SenhaWeb, Escola, Categoria}, Me.consultaOpcoesOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaOpcoesOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaOpcoesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaOpcoesCompleted(Me, New consultaOpcoesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaFicha", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaFicha(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal idDelib_cat As Integer, ByVal idDelib_des As Integer, ByVal notasfreq As Integer, ByVal nro_aluno As Integer) As String
            Dim results() As Object = Me.Invoke("consultaFicha", New Object() {UsuarioWeb, SenhaWeb, Escola, idDelib_cat, idDelib_des, notasfreq, nro_aluno})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaFichaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal idDelib_cat As Integer, ByVal idDelib_des As Integer, ByVal notasfreq As Integer, ByVal nro_aluno As Integer)
            Me.consultaFichaAsync(UsuarioWeb, SenhaWeb, Escola, idDelib_cat, idDelib_des, notasfreq, nro_aluno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaFichaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal idDelib_cat As Integer, ByVal idDelib_des As Integer, ByVal notasfreq As Integer, ByVal nro_aluno As Integer, ByVal userState As Object)
            If (Me.consultaFichaOperationCompleted Is Nothing) Then
                Me.consultaFichaOperationCompleted = AddressOf Me.OnconsultaFichaOperationCompleted
            End If
            Me.InvokeAsync("consultaFicha", New Object() {UsuarioWeb, SenhaWeb, Escola, idDelib_cat, idDelib_des, notasfreq, nro_aluno}, Me.consultaFichaOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaFichaOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaFichaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaFichaCompleted(Me, New consultaFichaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/preencherFicha", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function preencherFicha(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal idDelib_cat As Integer, ByVal idDelib_des As Integer, ByVal notasfreq As Integer, ByVal nro_aluno As Integer, ByVal Opcao_Exclusiva As Integer) As String
            Dim results() As Object = Me.Invoke("preencherFicha", New Object() {UsuarioWeb, SenhaWeb, Escola, idDelib_cat, idDelib_des, notasfreq, nro_aluno, Opcao_Exclusiva})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub preencherFichaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal idDelib_cat As Integer, ByVal idDelib_des As Integer, ByVal notasfreq As Integer, ByVal nro_aluno As Integer, ByVal Opcao_Exclusiva As Integer)
            Me.preencherFichaAsync(UsuarioWeb, SenhaWeb, Escola, idDelib_cat, idDelib_des, notasfreq, nro_aluno, Opcao_Exclusiva, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub preencherFichaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal idDelib_cat As Integer, ByVal idDelib_des As Integer, ByVal notasfreq As Integer, ByVal nro_aluno As Integer, ByVal Opcao_Exclusiva As Integer, ByVal userState As Object)
            If (Me.preencherFichaOperationCompleted Is Nothing) Then
                Me.preencherFichaOperationCompleted = AddressOf Me.OnpreencherFichaOperationCompleted
            End If
            Me.InvokeAsync("preencherFicha", New Object() {UsuarioWeb, SenhaWeb, Escola, idDelib_cat, idDelib_des, notasfreq, nro_aluno, Opcao_Exclusiva}, Me.preencherFichaOperationCompleted, userState)
        End Sub
        
        Private Sub OnpreencherFichaOperationCompleted(ByVal arg As Object)
            If (Not (Me.preencherFichaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent preencherFichaCompleted(Me, New preencherFichaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaCategoria", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaCategoria(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("consultaCategoria", New Object() {UsuarioWeb, SenhaWeb, Escola})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaCategoriaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String)
            Me.consultaCategoriaAsync(UsuarioWeb, SenhaWeb, Escola, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaCategoriaAsync(ByVal UsuarioWeb As String, ByVal SenhaWeb As String, ByVal Escola As String, ByVal userState As Object)
            If (Me.consultaCategoriaOperationCompleted Is Nothing) Then
                Me.consultaCategoriaOperationCompleted = AddressOf Me.OnconsultaCategoriaOperationCompleted
            End If
            Me.InvokeAsync("consultaCategoria", New Object() {UsuarioWeb, SenhaWeb, Escola}, Me.consultaCategoriaOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaCategoriaOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaCategoriaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaCategoriaCompleted(Me, New consultaCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub trazerFichaCompletedEventHandler(ByVal sender As Object, ByVal e As trazerFichaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class trazerFichaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub trazerFicha2CompletedEventHandler(ByVal sender As Object, ByVal e As trazerFicha2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class trazerFicha2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub trazerNroCompletedEventHandler(ByVal sender As Object, ByVal e As trazerNroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class trazerNroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GradeTurmaCompletedEventHandler(ByVal sender As Object, ByVal e As GradeTurmaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GradeTurmaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub idDelibNFCompletedEventHandler(ByVal sender As Object, ByVal e As idDelibNFCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class idDelibNFCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultaOpcoesCompletedEventHandler(ByVal sender As Object, ByVal e As consultaOpcoesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaOpcoesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultaFichaCompletedEventHandler(ByVal sender As Object, ByVal e As consultaFichaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaFichaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub preencherFichaCompletedEventHandler(ByVal sender As Object, ByVal e As preencherFichaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class preencherFichaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub consultaCategoriaCompletedEventHandler(ByVal sender As Object, ByVal e As consultaCategoriaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaCategoriaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
